-- =============================================================
-- Invekto.AgentAI Database Schema
-- Service: Invekto.AgentAI (port 7105)
-- Database: invekto (PostgreSQL, shared instance)
-- Convention: snake_case for all identifiers
-- =============================================================

-- Depends on: tenant-registry.sql (tenant_registry table)

-- =============================================================
-- suggest_reply_log: Logs every AI suggestion + agent feedback
-- =============================================================

CREATE TABLE IF NOT EXISTS suggest_reply_log (
    id                      BIGSERIAL PRIMARY KEY,
    suggestion_id           UUID NOT NULL UNIQUE,
    tenant_id               INTEGER NOT NULL REFERENCES tenant_registry(tenant_id),
    agent_id                INTEGER NOT NULL,
    chat_id                 INTEGER NOT NULL,
    channel                 VARCHAR(20),
    language                VARCHAR(5) NOT NULL DEFAULT 'tr',

    -- Request context
    message_text            TEXT NOT NULL,
    conversation_length     INTEGER NOT NULL DEFAULT 0,

    -- AI response
    suggested_reply         TEXT,
    intent                  VARCHAR(50),
    confidence              NUMERIC(4,3),
    model                   VARCHAR(100),
    processing_time_ms      INTEGER,

    -- Agent feedback (updated via POST /api/v1/feedback)
    agent_action            VARCHAR(20) DEFAULT 'pending',
    final_reply_text        TEXT,
    feedback_received_at    TIMESTAMPTZ,

    -- Timestamps
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT chk_agent_action CHECK (agent_action IN ('pending', 'accepted', 'edited', 'rejected')),
    CONSTRAINT chk_confidence CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_suggest_log_tenant_agent
    ON suggest_reply_log (tenant_id, agent_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_suggest_log_suggestion_id
    ON suggest_reply_log (suggestion_id);

CREATE INDEX IF NOT EXISTS idx_suggest_log_chat
    ON suggest_reply_log (tenant_id, chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_suggest_log_feedback
    ON suggest_reply_log (tenant_id, agent_id, agent_action)
    WHERE agent_action != 'pending';

-- =============================================================
-- Usage Notes
-- =============================================================
--
-- 1. suggest_reply_log is INSERT on suggest, UPDATE on feedback
-- 2. AgentProfileBuilder queries last 20 rows per (tenant_id, agent_id)
--    using idx_suggest_log_tenant_agent
-- 3. suggestion_id (UUID) is generated by AgentAI, returned in response,
--    and used by Main App to correlate feedback
-- 4. agent_action starts as 'pending', updated when feedback arrives
-- 5. final_reply_text is only populated for 'edited' action
-- =============================================================
