-- Migration 046: Kanban kartlarina "Ne ise yarar" + "Senaryo" prepend
--
-- Q istegi 2026-04-29: Her kartin baslangicina kisa aciklama + senaryo
-- ekle (DONE olanlar dahil hepsi). Drawer'da kart tiklandiginda body
-- ust kismi okunur, hizli orientation.
--
-- 69 UPDATE statement: 5 CUSTOMER + 34 DEV (D001-D034) + 9 DECISION (K003-K012)
-- + 9 OPS (O001-O009) + 9 UI (U001-U009) + 3 DOC (X001-X003) = 69 kart.
--
-- Idempotency: WHERE body_markdown NOT LIKE '%Ne ise yarar:%' — re-run sonrasi
-- 0 row match (no-op). COALESCE(body_markdown,'') NULL safety.
--
-- Format:
--   **🎯 Ne ise yarar:** {1 cumle ozet}
--   **📋 Senaryo:** {1 cumle pratik ornek}
--   ---
--   [mevcut body]
--
-- Postcondition INV-SEED-040: 69/69 kart "Ne ise yarar" icermeli.

-- §1. CUSTOMER (5 kart) — Musteri/3rd-party tarafi pre-pilot setup
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Meta''nin WhatsApp Business HSM template''ini onaylamasi (2026 policy: utility category 24-48h onay).\n\n**📋 Senaryo:** Pilot Day 0 oncesi welcome template Meta''ya submit edilir; reject olursa ayni gun ikinci versiyon submit, onay gelmedikce Stage 1 traffic baslamaz.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='C001' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Meta tarafinda musteri''nin Facebook sayfasi + Page Access Token + leadgen webhook subscription kurulumu.\n\n**📋 Senaryo:** Musteri "Doktor X Klinik" sayfasini olusturur, Q ekran paylasimiyla tokeni alir, INMA bridge config''ine yapistirir, webhook subscription Invekto callback URL''ine baglanir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='C002' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Musterinin Zoho CRM''inde lead pipeline (7 asama) Blueprint olarak tanimlanmasi.\n\n**📋 Senaryo:** Yeni hasta intake olunca Zoho''da "Yeni Aday"da acilir, mesaj cevaplaninca otomatik "Iletisim Kuruldu"ya gecer.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='C003' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Invekto''nun Zoho CRM''e OAuth ile baglanmasi + stage eslestirme dogrulamasi.\n\n**📋 Senaryo:** Lead status "interested"a gecince Zoho Blueprint''inde "Konusma Basladi" transition otomatik firlatilir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='C004' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** WABA onayli numara musteri tarafindan alinip phone_number_id INMA''ya tanitilir.\n\n**📋 Senaryo:** Musteri Meta''dan WABA numarasi alir, phone_number_id Q''ya iletir, INMA bridge tenant config''ine girilir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='C005' AND body_markdown NOT LIKE '%Ne ise yarar:%';

-- §2. DEV (D001-D034) — Yazilim gelistirme paketleri
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Production WhatsApp webhook fail orani %1+ asarsa Slack/email alert.\n\n**📋 Senaryo:** 5dk pencerede 100 webhook''tan 2 fail → #alerts kanalina mesaj.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D001' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** 7 gun ayni flow node''da kalmis lead''i flag + alert (drop-off detection).\n\n**📋 Senaryo:** Hasta Day 7''de hala "ai_faq_pricing" node''unda → koordinatore handoff bildirimi.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D002' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Tenant basi gunluk LLM maliyet limiti — %80 uyari, %100 hard stop.\n\n**📋 Senaryo:** Dent gunluk $50 limit, $40''a ulasinca uyari, $50 olunca yeni call''lar reddedilir + fallback message.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D003' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Intent confidence rolling 24h ortalamasi 3σ duserse anomaly alert.\n\n**📋 Senaryo:** Yeni FAQ varyanti devreye girdi, confidence %85 → %62 dustu → kotu performans alert.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D004' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Lead listesi + filtreler ekrani (Invekto Dashboard''da YAPILMAYACAK — INMA scope karari 2026-04-29).\n\n**📋 Senaryo:** Q karari sonrasi: lead listesi/filtre yonetimi INMA tarafinda; Invekto-side sadece tek-lead detay (D006) kalir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D005' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Tek-lead detay sayfasinda kronolojik etkilesim gecmisi (mesaj/status/randevu/foto/follow-up/not).\n\n**📋 Senaryo:** Koordinator hasta gecmisine bakar — "10:00 mesaj, 10:02 AI cevap, 10:15 randevu, 10:30 foto" tek timeline.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D006' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Slot tanimlama + takvim view + meeting link kopyalama + Zoho takvim cift yonlu sync.\n\n**📋 Senaryo:** Dr. Ozge takvimine Pazartesi 14:00 randevu acilir → Zoho''da appointment otomatik olusur.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D007' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Doktor CRUD + haftalik musaitlik grid + slot generation rule engine.\n\n**📋 Senaryo:** "Dr. Mehmet" Pazartesi 10-12 musait set edilir → otomatik 30dk''lik 4 slot generate olur.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D008' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Form → mesaj → randevu → gorusme → tedavi konversiyon huni gorseli.\n\n**📋 Senaryo:** Q "gecen hafta 100 lead, 30 cevap, 10 randevu, 3 tedavi" funnel okur, Day 3 dropoff''a focus eder.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D009' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** 12 welcome + 36 FAQ persona-zengin content + A/B rotation pool refresh.\n\n**📋 Senaryo:** Pilot Stage 3 sonrasi welcome generic''ten "Gunes + Dr. Ozge + Dublin tarihleri"ne gecer, A/B test ile en iyi varyant secilir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D010' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Production''da gercek Google Meet odasi + ICS calendar invite (Mock yerine).\n\n**📋 Senaryo:** Hasta randevu booked → Google Calendar''da event yaratilir → meet.google.com/abc-defg-hij gercek link gonderilir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D011' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Klinik iletisim + persona + roadshow tarihleri tenant config''e tasi (hardcoded literal cleanup).\n\n**📋 Senaryo:** Migration 040 sonrasi FAQ''larda "Dr. Ozge" yerine `{{team.dentist.name}}` placeholder; her tenant kendi adini config''den okur.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D012' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** INMA''da yeni firma acilinca Invekto otomatik default flow + template + feature flag yukler.\n\n**📋 Senaryo:** "ABC Klinik" tenant olusur → InmaTokenIntrospector welcome → ABC icin default flow + 12 FAQ + appointments=on flag populate.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D013' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** SuperAdmin TenantsPage''de tenant''i askiya al action butonu (is_active toggle).\n\n**📋 Senaryo:** Musteri faturayi odemedi → Q "Suspend" tiklar → tenant_registry.is_active=false, gelen webhook''lar 403 doner.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D014' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Instagram + Messenger + Twitter + TikTok + YouTube kanal genislemesi.\n\n**📋 Senaryo:** Hasta Instagram''dan "Dis tedavisi fiyatlari?" yazar → ayni flow engine cevaplar (birlesik agent inbox).\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D015' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Quote pipeline (Hazirlanyor → Hazirlandi → Verildi) otomatik gecisi.\n\n**📋 Senaryo:** Koordinator "teklif hazirliyorum" baslar → 30dk''da PDF olusur → otomatik "Hazirlandi" → gonderilince "Verildi"ye gecer.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D016' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Verilen teklif 24 saat icinde kabul edilmezse otomatik iptal/uyari.\n\n**📋 Senaryo:** Teklif 14:00''da gonderildi → 24 saat gecti cevap yok → "Teklif iptal" notify + lead "Cevap Verdi" stage''ine geri.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D017' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Donusum hunisi + A/B performans + akis KPI tablosu + dropoff (Dashboard rapor).\n\n**📋 Senaryo:** Q haftalik rapor — "Welcome A %62 cevap, B %48 → A kazandi, %14 dropoff Day 3 follow-up''ta".\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D018' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** INMA sohbet panelinde mevcut lead asamasini gosteren dropdown + cift yonlu sync (FEAT-PIPELINE).\n\n**📋 Senaryo:** Operator INMA panelinde sohbet acar → "Su anki: Cevap Verdi" gorur → "Ilgili"ye degistirir → Invekto + Zoho sync.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D019' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Pilot icin kritik 15 paketin top-level toplama karti (audit roll-up).\n\n**📋 Senaryo:** Q dashboard acar — "Pilot icin ne hazir?" sorusunun tek-bakista cevabi (D021-D026 alt-paket toplami).\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D020' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Meta Lead Ads form fill → Invekto webhook → leads tablosu native intake.\n\n**📋 Senaryo:** Facebook reklamindan hasta form doldurur → Meta webhook /api/inbound/meta/leadgen/{tenantId}''ye POST → leads''te yeni satir + welcome WA tetiklenir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D021' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Marketing-followup Hangfire queue dispatch fix — drip sequence dead-on-arrival sorununu cozer.\n\n**📋 Senaryo:** Lead intake → 3-stage drip schedule → Day 3''te FollowupStageJob queue''dan pickup → mesaj gonderilir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D022' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** doctors tablosu prod''a + 4 slot doctor_id backfill (Dent ilk Appointments user, latent schema gap fix).\n\n**📋 Senaryo:** VideoMeetingCreationJob "LEFT JOIN doctors d" artik calisir, meeting_link populate olur.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D023' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** tenant_settings.meta_leadgen_settings JSONB + webhook idempotency (B-META altyapisi).\n\n**📋 Senaryo:** Ayni Meta event 2 kez gelirse Invekto idempotency hash ile sadece 1 kez isler, dup lead engellenir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D024' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** leads.photo_status + sha256 idempotency + PhotoRequestService (foto isteme akisi altyapisi).\n\n**📋 Senaryo:** Hasta foto atti → SHA256 hash + tenant_id ile idempotent INSERT (ayni foto skip), photo_status REQUESTED → RECEIVED.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D025' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Dent tenant baslangic→kurumsal plan upgrade (Appointments feature unlock icin).\n\n**📋 Senaryo:** Dent appointments=true plan_guard kurumsal tier ister; baslangic''te 403, upgrade sonrasi 201 confirmed.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D026' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Outbound /broadcast/send''e INMA contact + Zoho COQL dis kaynak adapter (recipient list otomatik cekme).\n\n**📋 Senaryo:** Q "Dent''in Zoho''daki son 200 lead''ine roadshow campaign mesaji yolla" der → COQL query → recipient list → broadcast.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D027' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Medipol web sitesinde WhatsApp ikonu → KVKK modal → wa.me redirect (Doktorsitesi.com modeli).\n\n**📋 Senaryo:** Hasta Doc. Dr. Hayrettin profilinde WA tiklar → ad/soy/tel + KVKK onay → WhatsApp acilir hazir mesajla.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D028' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Server-side conversion tracking — Lead/Schedule/Purchase event''leri Meta''ya yollar (browser pixel iOS ITP yetersizliğini kapatir).\n\n**📋 Senaryo:** Hasta randevu booked → Marketing servisi Pixel''e Schedule event yollar → Meta reklam optimize, %10-15 ROAS artisi.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D029' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Meta reklam performans (spend/clicks/CTR/CPM/CPC + lead matching) Dashboard widget.\n\n**📋 Senaryo:** Q "Gecen 7 gun $1200 spend, 1500 click, 50 lead" gorur → CPL=$24 hesaplar, kotu kampanyalari kapatir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D030' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Reklam kampanya yonetimi Invekto Dashboard''dan (uzak hedef, $50k/ay spend gate).\n\n**📋 Senaryo:** Q "Dent icin $500 Dublin lead campaign ac" der → Invekto Marketing API ile Meta''da kampanya yaratilir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D031' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** 4 tenant_settings flag (enforce_message_category + enable_dynamic_message + efs_test_mode + efs_no_reply_threshold) toggle UI.\n\n**📋 Senaryo:** Q 2. musteri icin Settings → Advanced → flag''leri toggle eder, manuel SQL gereksiz.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D032' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Video provider Mock/GoogleMeet picker UI + config form.\n\n**📋 Senaryo:** Q yeni tenant onboarding''inde Mock vs GoogleMeet OAuth UI''dan radio secer + config doldurur.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D033' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** tenant_registry.settings_json (4 key) generic editor UI.\n\n**📋 Senaryo:** Q Dashboard''dan "Dent icin flow_builder_api_key rotate" tiklar, default_tone="professional" set eder.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='D034' AND body_markdown NOT LIKE '%Ne ise yarar:%';

-- §3. DECISION (K003-K012) — Q karar bekleyen/verilen kararlar
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Pilot lansmanda kac dil aktif olacak Q karari.\n\n**📋 Senaryo:** Hasta EN/TR yazar — AI ayni intent handler''i her iki dilde cevaplar (translation hop devrede).\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='K003' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Hasta fiyat sordugunda AI nasil cevap verecek karar.\n\n**📋 Senaryo:** Hasta "Ne kadar?" → AI faq_pricing "Tedavi plani kisiye ozel, online gorusme planlayalim" doner, randevu CTA gosterir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='K004' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Meta Ads kampanya sahipligi karari (butce + yonetim).\n\n**📋 Senaryo:** Musteri butce verir, Invekto kampanya kurar/optimize eder, haftalik raporla performans paylasilir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='K005' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Calisma saatleri disinda gelen mesajlara nasil yanit verilecek karar.\n\n**📋 Senaryo:** Gece 02:00''de hasta yazar → AI agent 24/7 aktif cevaplar; mesai basinda koordinator handoff''lari inceler.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='K006' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Sistem anlamadiginda devreye girecek koordinator kim (isim + WhatsApp + e-posta).\n\n**📋 Senaryo:** AI 2 retry sonrasi "anlamadi" → koordinatore handoff mesaji, 5dk icinde manuel cevap yazar.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='K007' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Dr. Ozge gunluk online gorusme kapasitesi karari.\n\n**📋 Senaryo:** Slot generation buna gore (1 saat aralikli 4 slot, 10:00-15:00); 5. hasta randevu istese "kontenjan dolu, yarin" cevabi.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='K008' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Lead/sohbet retention period karari (GDPR + ticari ihtiyac dengesi).\n\n**📋 Senaryo:** Hasta "verimi silin" der → koordinator tetikler → 30 gun sonra otomatik silme; saklama suresi karari retention''i belirler.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='K010' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** FEAT-PHOTO foto isteme akisi pilotta hangi modda aktif (manuel/yari-otomatik/tam otomatik/kapali).\n\n**📋 Senaryo:** Hasta dis tedavisi sorar → sistem foto isteyebilir mi? Manuel: koordinator elle. Yari-otomatik: sistem oner, koordinator onay.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='K011' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Lead pipeline tanimi sahipligi (asama isimleri/sirasi/kurallari) INMA''da olacak.\n\n**📋 Senaryo:** Yeni asama eklenmesi gerekirse INMA admin paneli uzerinden eklenir, Invekto + Zoho INMA''dan ceker (FEAT-PIPELINE 3-way sync).\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='K012' AND body_markdown NOT LIKE '%Ne ise yarar:%';

-- §4. OPS (O001-O009) — Invekto operasyon
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Tenant ayarlari + LIW + VCP + MCC + EFS + TFM + Templates + Meta Leadgen toplu kurulum.\n\n**📋 Senaryo:** Q yeni tenant icin 8 settings sayfasini ardisik kurar (~2-3 saat). 5/8 hazir; 3 eksik (E.1+E.3+E.7).\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='O001' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** WABA numarasini INMA tarafinda allowlist + Dashboard bridge test.\n\n**📋 Senaryo:** Q test mesajlari yollar (5 numara), bridge''ten Invekto webhook''a duser, log''da "INV-BRIDGE-OK" gorunur.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='O002' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Stage 1 Day 1 happy path smoke (5 numara × 6 senaryo = 30 ko-execution test).\n\n**📋 Senaryo:** F.1: Form → karsilama → Dublin → saat → fiyat → randevu → Meet linki, hepsi yesil; 0 critical bug + temiz alert.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='O003' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Stage 1 Day 2 edge case + monitoring dogrulama.\n\n**📋 Senaryo:** Sinir disi mesaj + cift kayit + saat dolmus slot + foto formati gecersiz + mesai disi mesaj — hepsi expected behavior gosterir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='O004' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Stage 1 Go/No-Go Q sign-off kriteri.\n\n**📋 Senaryo:** 30 senaryo cikti + 0 critical bug + temiz log + Q "GO" → Stage 2 traffic %25 baslar; FAIL ise rollback.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='O005' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Koordinator Dashboard 15 dk video egitim.\n\n**📋 Senaryo:** Lead listesi + manuel mesaj + teklif + override anlatilir, koordinator Day 0 oncesi izler.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='O006' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** AI Supervise 10 dk video — handoff + intent log.\n\n**📋 Senaryo:** AI ne zaman handoff yapar, intent log nasil okunur, FAQ varyanti ekleme — koordinator egitimi.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='O007' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Pilot oncesi 30dk acilis toplantisi (yonetim + koordinator + Dr. Ozge).\n\n**📋 Senaryo:** Sistem demo + senaryo demo + Q&A — pilot Day 0 oncesi tum ekibin sistemi anlamasi saglanir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='O008' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** 5 madde pre-smoke verify gate (gercek drift cycle sebep eden contract quirks).\n\n**📋 Senaryo:** Header X-Invekto-Api-Key + body fields wrapper + consent boolean + slug regex dash-only + localhost direct URL — bu 5 quirk smoke FAIL sebebidir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='O009' AND body_markdown NOT LIKE '%Ne ise yarar:%';

-- §5. UI (U001-U009) — UI ekrani eksik feature gaps
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Robot anlayamayinca devredilen hastalarin koordinator aksiyon ekrani (handoff inbox).\n\n**📋 Senaryo:** Hasta "anlamadi" → koordinator inbox''unda "5 hasta cevap bekliyor" → tikla, manuel cevap, claim, release.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='U001' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Eskalasyon + hata + kapasite + anomali bildirimleri tek panelde toplama.\n\n**📋 Senaryo:** AI cost limit %95''e ulasti → bildirim merkezinde kirmizi bell, koordinator detay gorur, aksiyon alir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='U002' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Online gorusme oncesi 1 saatlik hazirlik ekrani (Dr. Ozge brifing).\n\n**📋 Senaryo:** 10:00 gorusme → 09:00''da brifing acar — hasta formu + sohbet ozeti + foto thumbnail + onceki notlar tek bakista.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='U003' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Teklif lifecycle 3 ara durum (Hazirlanyor/Hazirlandi/Verildi) + content editor.\n\n**📋 Senaryo:** Koordinator "Teklif hazirla" tiklar → fiyat kalemleri + paket notu + gonder → otomatik PDF + WhatsApp gonderim.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='U004' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Gunluk operasyon dashboard ana sayfasi (operasyon komuta).\n\n**📋 Senaryo:** Q sabah acar — "Bugun 12 hasta + 8 randevu + 2 eskalasyon + 3 gorusme" tek bakista, klinik durumu ozet.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='U005' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Hasta veri silme talebi tek tikla tetikleme (GDPR compliance UI).\n\n**📋 Senaryo:** Hasta "verimi silin" der → koordinator tiklar "Verimi Sil" → onay modali → 30 gun schedule''li silme tetiklenir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='U006' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Lead-bazli "kim ne zaman ne degistirdi" timeline (audit log goruntulemesi).\n\n**📋 Senaryo:** Q "neden bu lead lost''a gecti?" sorar → audit log: "10:30 koordinator manuel status=lost", kanit gorur.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='U007' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Stage 3''te 100 lead''e tek seferde mesaj (FEAT-OBI ile birlesir).\n\n**📋 Senaryo:** Roadshow yaklasiyor, Q "gecen ay Dublin lead''lerine kampanya" → segment + template + send → 100 mesaj WhatsApp''tan dagilir.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='U008' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Olumsuz mesajlari tag + escalation flow (sentiment-based sikayet yonetimi).\n\n**📋 Senaryo:** Hasta "berbatti, bir daha gelmem" → sentiment=negative → otomatik tag "sikayet" + koordinatore WhatsApp uyari.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='U009' AND body_markdown NOT LIKE '%Ne ise yarar:%';

-- §6. DOC (X001-X003) — Doku/tracking
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** Gunes anlamadiginda ne yapacagini gosteren 1-sayfa cheatsheet (escalation karti).\n\n**📋 Senaryo:** Koordinator masaustunde 1-sayfa cheatsheet — anlamayan AI 2 retry sonrasi handoff; olumsuz duygu direkt handoff; override AI durdur.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='X001' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** lessons-learned.md 422 entry token disiplini icin arsive tasi (50 esik asti).\n\n**📋 Senaryo:** Son 3 ay aktif kalir, eskileri arch/lessons-learned-archive.md''ye tasinir; session bootstrap''ta archive ASLA tam Read edilmez.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='X002' AND body_markdown NOT LIKE '%Ne ise yarar:%';
UPDATE kanban_cards SET body_markdown = E'**🎯 Ne ise yarar:** dent-toplanti.html''den 6 yeni section dent-golive.html''e konsolidasyon (doc cleanup).\n\n**📋 Senaryo:** §19 Toplanti Soru Katalogu + §20 Karar Tablosu K1-K10 + §21 Musteri SSS + §22 Lead Asamalari + §23 DocX eslestirme + §24 6 senaryo.\n\n---\n\n' || COALESCE(body_markdown,''), updated_at=NOW() WHERE board_key='inse' AND ref_code='X003' AND body_markdown NOT LIKE '%Ne ise yarar:%';

-- §7. Postcondition guard
DO $verify$
DECLARE
    pending integer;
    total integer;
BEGIN
    SELECT COUNT(*) INTO total FROM kanban_cards WHERE board_key='inse';
    SELECT COUNT(*) INTO pending FROM kanban_cards WHERE board_key='inse' AND body_markdown NOT LIKE '%Ne ise yarar:%';

    IF pending > 0 THEN
        RAISE EXCEPTION '[INV-SEED-040] Migration 046: % kart hala "Ne ise yarar" bolumu icermiyor (toplam % kart).', pending, total;
    END IF;

    RAISE NOTICE 'Migration 046 OK: % / % kart "Ne ise yarar" + "Senaryo" bolumune sahip.', total - pending, total;
END$verify$;
