namespace Invekto.Shared.DTOs.AgentAI;

/// <summary>PKT-6B1 GR-3.3: Order card for agent assist sidebar (fetched from Integrations).</summary>
public sealed class OrderCardResponse
{
    public string? CustomerPhone { get; set; }
    public List<OrderCardItem> Orders { get; set; } = new();
    public string? Warning { get; set; }
}

/// <summary>Single order summary for the order card.</summary>
public sealed class OrderCardItem
{
    public string Provider { get; set; } = "";
    public string ExternalOrderId { get; set; } = "";
    public string Status { get; set; } = "";
    public decimal? TotalAmount { get; set; }
    public string? Currency { get; set; }
    public string? TrackingCode { get; set; }
    public string? CreatedAt { get; set; }
}

/// <summary>Escalation note generated by AI on handoff (GR-3.3.2).</summary>
public sealed class EscalationNoteResponse
{
    public string Summary { get; set; } = "";
    public string Intent { get; set; } = "";
    public string Sentiment { get; set; } = "";
    public List<string> KeyPoints { get; set; } = new();
}
